export interface Product {
  id: string;
  name: string;
  tagline: string;
  description: string;
  category: "product" | "hidden";
  color: string;
  bgColor: string;
  icon: string;
  logo?: string;
  features: string[];
  useCases: string[];
  howItWorks: string[];
  appUrl: string;
}

export const products: Product[] = [
  {
    id: "groupcheers",
    name: "GroupCheers",
    logo: "/logo-groupcheers.svg",
    tagline: "Celebrate together, beautifully.",
    description:
      "Create stunning group greeting cards for birthdays, farewells, work anniversaries, and every celebration. Invite your team to sign, add GIFs, photos, and heartfelt messages — then deliver a beautiful digital card that feels personal.",
    category: "product",
    color: "text-purple-600",
    bgColor: "bg-purple-500/10",
    icon: "🎉",
    features: [
      "Beautiful card templates for every occasion",
      "Invite unlimited signers via email or link",
      "Add GIFs, stickers, photos, and drawings",
      "Schedule delivery for the perfect moment",
      "Slack & Microsoft Teams integration",
      "Custom branding with your company logo",
      "Print-ready PDF export",
      "Real-time collaboration — watch the card fill up",
    ],
    useCases: [
      "Birthday celebrations for remote teams",
      "Employee farewell and going-away cards",
      "Work anniversary milestones",
      "Thank you cards for clients and partners",
      "Holiday greetings across the company",
      "Welcome cards for new team members",
    ],
    howItWorks: [
      "Create a card — pick a template and customize it",
      "Invite signers — share a link or send email invites",
      "Everyone signs — messages, GIFs, photos, stickers",
      "Deliver the card — schedule or send instantly",
    ],
    appUrl: "https://groupcheers.microooo.com",
  },
  {
    id: "echoboard",
    name: "EchoBoard",
    logo: "/logo-echoboard.svg",
    tagline: "Hear your users. Ship what matters.",
    description:
      "A complete feedback management suite. Collect feature requests, build a public roadmap, and publish changelogs — all in one place. Let your users vote on what matters most so you ship the right things.",
    category: "product",
    color: "text-blue-600",
    bgColor: "bg-blue-500/10",
    icon: "💬",
    features: [
      "Public feature request boards",
      "User voting and prioritization",
      "Visual public roadmap",
      "Changelog with rich media support",
      "Custom statuses (Planned, In Progress, Done)",
      "Email notifications for status updates",
      "Embeddable widgets for your app",
      "Custom domain support",
    ],
    useCases: [
      "SaaS products collecting user feedback",
      "Startups validating feature ideas",
      "Product teams prioritizing the backlog",
      "Open-source projects with community input",
      "Agencies managing client requests",
      "Internal teams tracking improvement ideas",
    ],
    howItWorks: [
      "Set up your board — customize categories and statuses",
      "Share with users — embed in your app or share the link",
      "Collect votes — users upvote the features they want",
      "Ship & announce — move items through your roadmap and publish changelogs",
    ],
    appUrl: "https://echoboard.microooo.com",
  },
  {
    id: "socialpull",
    name: "SocialPull",
    logo: "/logo-socialpull.svg",
    tagline: "All your social feeds. One beautiful wall.",
    description:
      "Aggregate content from Instagram, Twitter, YouTube, TikTok, and more into a single, embeddable social wall. Perfect for websites, events, and digital displays. Moderate content before it goes live.",
    category: "product",
    color: "text-purple-600",
    bgColor: "bg-purple-500/10",
    icon: "📱",
    features: [
      "Pull from 10+ social platforms",
      "Beautiful grid, carousel, and wall layouts",
      "Real-time content updates",
      "Content moderation and filtering",
      "Embeddable responsive widgets",
      "Custom branding and themes",
      "Hashtag and mention tracking",
      "Analytics on engagement and reach",
    ],
    useCases: [
      "Event social walls and live displays",
      "Website social proof sections",
      "Brand monitoring dashboards",
      "User-generated content curation",
      "Digital signage in offices and stores",
      "Marketing campaign tracking",
    ],
    howItWorks: [
      "Connect sources — link your social accounts and hashtags",
      "Curate content — approve, reject, or auto-publish",
      "Design your wall — pick a layout and customize the look",
      "Embed anywhere — drop the widget into your site or display",
    ],
    appUrl: "https://socialpull.microooo.com",
  },
  {
    id: "stepwise",
    name: "StepWise",
    logo: "/logo-stepwise.svg",
    tagline: "Onboard users like a pro.",
    description:
      "Build interactive product tours, tooltips, and onboarding checklists without writing code. Guide new users through your app step-by-step and boost activation rates. No SDK required — just paste a script tag.",
    category: "product",
    color: "text-green-600",
    bgColor: "bg-green-500/10",
    icon: "🚀",
    features: [
      "Drag-and-drop tour builder",
      "Smart tooltips with targeting",
      "Onboarding checklists with progress tracking",
      "User segmentation and targeting rules",
      "A/B testing for different flows",
      "Analytics on completion rates",
      "No-code — just a script tag",
      "Custom themes to match your brand",
    ],
    useCases: [
      "SaaS product onboarding",
      "Feature adoption campaigns",
      "In-app announcements and updates",
      "User education and training",
      "Reducing support tickets",
      "Increasing trial-to-paid conversion",
    ],
    howItWorks: [
      "Install the script — one line of code, done",
      "Build your tour — point-and-click on your live app",
      "Set triggers — who sees it and when",
      "Launch and measure — track completion and drop-off",
    ],
    appUrl: "https://stepwise.microooo.com",
  },
  {
    id: "screencast",
    name: "ScreenCast",
    logo: "/logo-screencast.svg",
    tagline: "Digital signage, simplified.",
    description:
      "Turn any screen into a dynamic digital display. Push content to TVs, monitors, and kiosks from your dashboard. Schedule playlists, show live data, and manage screens across locations — all from one place.",
    category: "product",
    color: "text-orange-600",
    bgColor: "bg-orange-500/10",
    icon: "🖥️",
    features: [
      "Remote screen management",
      "Content scheduling and playlists",
      "Live data widgets (weather, news, metrics)",
      "Multi-location support",
      "Team collaboration",
      "Offline mode — content keeps playing",
      "Portrait and landscape support",
      "Custom templates and layouts",
    ],
    useCases: [
      "Office lobby and meeting room displays",
      "Restaurant and cafe menu boards",
      "Retail store promotions",
      "Event information screens",
      "Company KPI dashboards on TVs",
      "School and university announcements",
    ],
    howItWorks: [
      "Add a screen — install the player on any device",
      "Create content — use templates or upload your own",
      "Schedule playlists — set what plays when",
      "Manage remotely — update content from anywhere",
    ],
    appUrl: "https://screencast.microooo.com",
  },
  {
    id: "ogsnap",
    name: "OGSnap",
    tagline: "Beautiful OG images. Zero design work.",
    description:
      "Generate stunning Open Graph images for your website, blog posts, and social shares automatically. Pick a template, connect your content, and every page gets a perfect preview image when shared on social media.",
    category: "hidden",
    color: "text-indigo-600",
    bgColor: "bg-indigo-500/10",
    icon: "🖼️",
    features: [
      "50+ professionally designed templates",
      "Dynamic text and image injection",
      "REST API for programmatic generation",
      "Custom fonts and brand colors",
      "Automatic caching and CDN delivery",
      "Real-time preview editor",
      "Batch generation for multiple pages",
      "SVG and PNG output formats",
    ],
    useCases: [
      "Blog post social previews",
      "Product page share images",
      "Event announcement cards",
      "Documentation page previews",
      "E-commerce product shares",
      "Newsletter social cards",
    ],
    howItWorks: [
      "Pick a template — browse the gallery",
      "Customize — set your brand colors and fonts",
      "Generate — use the API or dashboard",
      "Deploy — images are cached on our CDN globally",
    ],
    appUrl: "https://ogsnap.microooo.com",
  },
  {
    id: "legalkit",
    name: "LegalKit",
    tagline: "Legal pages in 60 seconds.",
    description:
      "Generate professional privacy policies, terms of service, cookie policies, and GDPR compliance pages for your website. Answer a few questions and get legally-sound pages ready to publish. Stay compliant without hiring a lawyer.",
    category: "hidden",
    color: "text-amber-600",
    bgColor: "bg-amber-500/10",
    icon: "⚖️",
    features: [
      "Privacy Policy generator",
      "Terms of Service generator",
      "Cookie Policy with consent banner",
      "GDPR and CCPA compliant templates",
      "Customizable to your business type",
      "Auto-updates when laws change",
      "Embeddable or hosted pages",
      "Multiple language support",
    ],
    useCases: [
      "SaaS products needing legal pages",
      "E-commerce stores",
      "Mobile app privacy policies",
      "Freelancer and agency websites",
      "Startup compliance requirements",
      "Blog and content site policies",
    ],
    howItWorks: [
      "Answer questions — about your business and data practices",
      "Generate pages — we create legally-compliant documents",
      "Publish — embed on your site or use our hosted page",
      "Stay updated — we notify you when laws change",
    ],
    appUrl: "https://legalkit.microooo.com",
  },
  {
    id: "snapshot",
    name: "SnapShot",
    tagline: "Screenshot any URL. Instantly.",
    description:
      "A powerful screenshot API that captures any webpage as a high-quality image. Perfect for generating thumbnails, building preview cards, monitoring visual changes, and automating screenshot workflows.",
    category: "hidden",
    color: "text-cyan-600",
    bgColor: "bg-cyan-500/10",
    icon: "📸",
    features: [
      "Full-page and viewport screenshots",
      "Custom viewport sizes (desktop, tablet, mobile)",
      "Wait for page load and animations",
      "Block ads and cookie banners",
      "PDF capture mode",
      "Scheduled recurring screenshots",
      "Webhook notifications",
      "S3 and custom storage integration",
    ],
    useCases: [
      "Website thumbnail generation",
      "Visual regression testing",
      "Social media preview cards",
      "Competitor monitoring",
      "Portfolio and showcase sites",
      "Automated reporting with screenshots",
    ],
    howItWorks: [
      "Get your API key — sign up and grab it",
      "Make a request — pass the URL and options",
      "Get the image — PNG, JPEG, or PDF returned",
      "Scale it — process thousands of screenshots per hour",
    ],
    appUrl: "https://snapshot.microooo.com",
  },
  {
    id: "topbar",
    name: "TopBar",
    tagline: "Announce anything. Beautifully.",
    description:
      "Add eye-catching announcement bars to your website in seconds. Promote sales, announce features, share news, or collect emails — with beautiful, customizable bars that grab attention without being annoying.",
    category: "product",
    color: "text-red-600",
    bgColor: "bg-red-500/10",
    icon: "📢",
    features: [
      "Drag-and-drop bar designer",
      "Countdown timers for urgency",
      "Email capture built-in",
      "A/B testing",
      "Page-level targeting rules",
      "Mobile-responsive designs",
      "Custom CSS support",
      "Analytics and click tracking",
    ],
    useCases: [
      "Product launch announcements",
      "Black Friday and sale promotions",
      "Maintenance and downtime notices",
      "Newsletter signup collection",
      "Cookie consent notifications",
      "Seasonal campaigns",
    ],
    howItWorks: [
      "Design your bar — pick colors, text, and CTA",
      "Set targeting — which pages and who sees it",
      "Install — one script tag on your site",
      "Track results — see clicks, conversions, dismissals",
    ],
    appUrl: "https://topbar.microooo.com",
  },
  {
    id: "signmail",
    name: "SignMail",
    tagline: "Professional email signatures. Instantly.",
    description:
      "Create beautiful, consistent email signatures for your entire team. Design once, deploy everywhere. Works with Gmail, Outlook, Apple Mail, and more. Include social links, banners, and call-to-action buttons.",
    category: "hidden",
    color: "text-violet-600",
    bgColor: "bg-violet-500/10",
    icon: "✉️",
    features: [
      "Visual signature designer",
      "50+ professional templates",
      "Team-wide deployment",
      "Banner campaigns for promotions",
      "Social media icon integration",
      "Works with all major email clients",
      "Click tracking on links",
      "Custom fonts and brand colors",
    ],
    useCases: [
      "Company-wide signature standardization",
      "Marketing campaigns via email banners",
      "Professional freelancer branding",
      "Sales team contact signatures",
      "Event promotion through email footers",
      "New employee onboarding",
    ],
    howItWorks: [
      "Design — use the visual builder or pick a template",
      "Customize — add your info, photo, and social links",
      "Install — one-click install for Gmail, Outlook, etc.",
      "Manage — update everyone's signature from one dashboard",
    ],
    appUrl: "https://signmail.microooo.com",
  },
  {
    id: "pingbadge",
    name: "PingBadge",
    tagline: "Show your uptime. Build trust.",
    description:
      "Monitor your website's uptime and display beautiful status badges on your site. Show visitors your reliability with real-time uptime percentages, response times, and incident history. Build trust through transparency.",
    category: "hidden",
    color: "text-emerald-600",
    bgColor: "bg-emerald-500/10",
    icon: "🟢",
    features: [
      "60-second monitoring intervals",
      "Beautiful embeddable status badges",
      "Public status page",
      "Downtime alerts via email, Slack, SMS",
      "Response time graphs",
      "Multi-region monitoring",
      "SSL certificate expiry alerts",
      "Incident management",
    ],
    useCases: [
      "SaaS product status pages",
      "Agency client reporting",
      "E-commerce site monitoring",
      "API endpoint health checks",
      "Landing page trust signals",
      "Internal infrastructure monitoring",
    ],
    howItWorks: [
      "Add your URLs — tell us what to monitor",
      "We ping it — from multiple global regions every 60 seconds",
      "Get alerted — email, Slack, or SMS when something's down",
      "Show the badge — embed your uptime badge on your site",
    ],
    appUrl: "https://pingbadge.microooo.com",
  },
  {
    id: "favicon",
    name: "Favicon",
    tagline: "Perfect favicons. Every browser.",
    description:
      "Generate all the favicon sizes and formats you need from a single image. Get ICO, PNG, SVG, Apple Touch Icon, and web manifest files — everything your site needs to look perfect in every browser and device.",
    category: "hidden",
    color: "text-sky-600",
    bgColor: "bg-sky-500/10",
    icon: "🎯",
    features: [
      "Generate all favicon sizes from one image",
      "ICO, PNG, SVG output formats",
      "Apple Touch Icon generation",
      "Web manifest file included",
      "Browser preview before download",
      "Emoji-to-favicon converter",
      "Text-to-favicon generator",
      "Bulk generation for multiple projects",
    ],
    useCases: [
      "New website launches",
      "Rebranding projects",
      "Web app PWA setup",
      "Browser tab identification",
      "Bookmark and home screen icons",
      "Multi-site favicon management",
    ],
    howItWorks: [
      "Upload your image — or type an emoji",
      "Preview — see how it looks in every browser",
      "Download — get the complete favicon package",
      "Install — copy the HTML snippet to your site",
    ],
    appUrl: "https://favicon.microooo.com",
  },
  {
    id: "golink",
    name: "GoLink",
    tagline: "Smart redirects. Zero downtime.",
    description:
      "Create and manage URL redirects without touching your server config. Perfect for marketing campaigns, link shortening, A/B testing landing pages, and managing URL migrations. Real-time analytics on every redirect.",
    category: "product",
    color: "text-teal-600",
    bgColor: "bg-teal-500/10",
    icon: "🔗",
    features: [
      "Instant redirect creation",
      "301 and 302 redirect types",
      "Wildcard and regex patterns",
      "Click analytics and referrer tracking",
      "Geographic and device targeting",
      "Bulk import/export",
      "API for programmatic management",
      "Custom short domains",
    ],
    useCases: [
      "Marketing campaign tracking links",
      "Website migration URL mapping",
      "Short URLs for print materials",
      "A/B testing landing pages",
      "Affiliate link management",
      "QR code destination management",
    ],
    howItWorks: [
      "Create a redirect — set the source and destination",
      "Configure rules — targeting, type, and expiry",
      "Deploy instantly — redirects go live immediately",
      "Track performance — see clicks, sources, and conversions",
    ],
    appUrl: "https://golink.microooo.com",
  },
  {
    id: "pricecard",
    name: "PriceCard",
    tagline: "Pricing pages that convert.",
    description:
      "Build beautiful, high-converting pricing pages without design skills. Choose from proven templates, customize your plans, and embed on your site. A/B test different layouts and pricing strategies to maximize conversions.",
    category: "hidden",
    color: "text-lime-600",
    bgColor: "bg-lime-500/10",
    icon: "💰",
    features: [
      "Proven high-converting templates",
      "Toggle between monthly/annual pricing",
      "Feature comparison tables",
      "Custom CTA buttons and links",
      "Embeddable on any website",
      "A/B testing built-in",
      "Mobile-responsive designs",
      "Analytics on plan selection",
    ],
    useCases: [
      "SaaS product pricing pages",
      "Freelancer service packages",
      "Course and membership tiers",
      "Agency service offerings",
      "E-book and digital product pricing",
      "Consulting rate cards",
    ],
    howItWorks: [
      "Pick a template — browse proven layouts",
      "Add your plans — set features, prices, and CTAs",
      "Customize the look — match your brand",
      "Embed or host — drop it on your site or use our page",
    ],
    appUrl: "https://pricecard.microooo.com",
  },
  {
    id: "pausepage",
    name: "PausePage",
    tagline: "Beautiful downtime pages.",
    description:
      "Create professional maintenance and coming-soon pages that keep your visitors informed and your brand looking good — even when your site is down. Set up automatic scheduling so your maintenance page appears and disappears on time.",
    category: "hidden",
    color: "text-stone-600",
    bgColor: "bg-stone-500/10",
    icon: "⏸️",
    features: [
      "Beautiful maintenance page templates",
      "Coming soon pages with email capture",
      "Countdown timers",
      "Scheduled activation and deactivation",
      "Custom domain support",
      "IP whitelist for team access",
      "Social media links",
      "Progress bars for launch milestones",
    ],
    useCases: [
      "Scheduled maintenance windows",
      "Coming soon / pre-launch pages",
      "Emergency downtime communication",
      "Website redesign transitions",
      "Product launch countdowns",
      "Seasonal business closures",
    ],
    howItWorks: [
      "Design your page — pick a template and customize",
      "Set the schedule — when to activate and deactivate",
      "Configure access — whitelist your team's IPs",
      "Go live — your maintenance page handles the rest",
    ],
    appUrl: "https://pausepage.microooo.com",
  },
];

export const visibleProducts = products.filter(p => p.category === "product");
